# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-22 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True, max_length=2000)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('image_md5', models.CharField(editable=False, max_length=32)),
                ('link_url', models.URLField(blank=True, max_length=256)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
