//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: pbuf_multicast.proto
// Note: requires additional types generated from: funapi/service/multicast_message.proto
namespace pbuf_multicast
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PbufHelloMessage")]
  public partial class PbufHelloMessage : global::ProtoBuf.IExtensible
  {
    public PbufHelloMessage() {}
    
    private string _message = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}