//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: funapi/network/fun_message.proto
namespace funapi.network.fun_message
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FunMessage")]
  public partial class FunMessage : global::ProtoBuf.IExtensible
  {
    public FunMessage() {}
    

    private string _sid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"sid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string sid
    {
      get { return _sid; }
      set { _sid = value; }
    }

    private string _msgtype = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"msgtype", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string msgtype
    {
      get { return _msgtype; }
      set { _msgtype = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}