//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: funapi/network/maintenance.proto
// Note: requires additional types generated from: funapi/network/fun_message.proto
namespace funapi.network.maintenance
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MaintenanceMessage")]
  public partial class MaintenanceMessage : global::ProtoBuf.IExtensible
  {
    public MaintenanceMessage() {}
    
    private string _date_start = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"date_start", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string date_start
    {
      get { return _date_start; }
      set { _date_start = value; }
    }
    private string _date_end = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"date_end", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string date_end
    {
      get { return _date_end; }
      set { _date_end = value; }
    }
    private string _messages = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"messages", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string messages
    {
      get { return _messages; }
      set { _messages = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}